#!/usr/bin/env dlsh
#
# test_dg_names.tcl
#   What a dyngroup is called, and who gets to decide.
#
#   A serialized group carries the name it had where it was made. That name
#   means two different things depending on where it came from:
#
#     groupNNN   generated by dg_create from that interpreter's counter. It
#                identifies nothing here -- two unrelated groups can easily
#                both be group7 -- so a restore renames it locally and the
#                caller keeps whatever dg_fromString returned.
#
#     stimdg     chosen by a person. Code refers to it by name, and restoring
#                over it to replace the contents is the whole point, so the
#                name survives the trip.
#
#   The generated names are also never reused: the counter does not restart
#   on dg_clean, and dg_create steps over any name already taken. Before that,
#   restoring a group7 into a fresh interpreter made the eighth dg_create fail
#   outright with "tclPutGroup: group group7 already exists".
#
#   Usage: dlsh test_dg_names.tcl

if {[catch {package require dlsh}]} {
    foreach path {/usr/local/dlsh/dlsh.zip /usr/local/lib/dlsh.zip} {
        if {[file exists $path]} {
            catch {zipfs mount $path /dlsh}
            set base [file join [zipfs root] dlsh]
            set ::auto_path [linsert $::auto_path 0 ${base}/lib]
            break
        }
    }
    package require dlsh
}

set ::failures 0
proc check {name got want} {
    if {$got eq $want} {
        puts "OK   $name"
    } else {
        puts "FAIL $name -> got {$got} want {$want}"
        incr ::failures
    }
}
proc reset {} {
    catch {dg_clean}
    foreach g [dg_dir] { catch {dg_delete $g} }
    catch {dl_clean}
}

# --- an anonymous group is renamed on arrival ----------------------------
reset
foreach i {0 1 2 3 4 5 6} { dg_create }
set src [dg_create]
check "source group is anonymous" $src group7
dl_set $src:col [dl_ilist 111 222 333]
dg_toString64 $src blob
reset

set r [dg_fromString64 $blob]
check "restored under a local name" [expr {$r ne "group7"}] 1
check "contents came through"       [dl_tcllist $r:col] {111 222 333}

# and it does not collide with anything made afterwards
set made {}
for {set i 0} {$i < 12} {incr i} { lappend made [dg_create] }
check "no generated name repeats" \
    [llength [lsort -unique [concat $made $r]]] 13
check "restored group survives all of that" [dl_tcllist $r:col] {111 222 333}

# --- a chosen name is preserved, and replaces in place -------------------
reset
set s [dg_create stimdg]
dl_set $s:A [dl_ilist 1 1 1]
dg_toString64 $s blob2
dg_delete $s

set r2 [dg_fromString64 $blob2]
check "chosen name survives the round trip" $r2 stimdg
check "reachable by that name, as callers do" [dl_tcllist stimdg:A] {1 1 1}

# restoring again replaces rather than accumulating -- essgui and ess-2.0
# both call dg_fromString64 bare and then use the name
set before [llength [dg_dir]]
for {set i 0} {$i < 10} {incr i} { dg_fromString64 $blob2 }
check "repeated restore replaces in place" [llength [dg_dir]] $before
check "still reachable by name"            [dl_tcllist stimdg:A] {1 1 1}

# --- an explicit target name wins over both ------------------------------
reset
set r3 [dg_fromString64 $blob mycopy]
check "explicit name is used"     $r3 mycopy
check "contents came through"     [dl_tcllist mycopy:col] {111 222 333}
set r4 [dg_fromString64 $blob2 mycopy]
check "explicit name replaces"    $r4 mycopy
check "with the new contents"     [dl_tcllist mycopy:A] {1 1 1}
check "and the old column is gone" [catch {dl_tcllist mycopy:col}] 1

# --- counters do not restart --------------------------------------------
reset
set a [dg_create]
dg_clean
set b [dg_create]
check "dg_clean does not restart the counter" [expr {$a ne $b}] 1

set x [dl_ilist 1 2 3]
set name [string range " $x" 1 end]
dl_clean
set y [dl_fromto 0 7]
check "a freed list name is not handed out again" \
    [expr {$name eq [string range " $y" 1 end]}] 0
check "and resolving the old name fails rather than finding another list" \
    [catch {dl_length $name}] 1

# --- nothing leaked along the way ----------------------------------------
reset
set n0 [llength [dl_dir]]
for {set i 0} {$i < 50} {incr i} { dg_delete [dg_fromString64 $blob] }
check "restoring and deleting 50 times leaves no lists behind" \
    [expr {[llength [dl_dir]] - $n0}] 0

if {$::failures} {
    puts "FAILURES: $::failures"
    exit 1
}
puts "all dyngroup naming tests passed"
exit 0
