# demo_conditions.tcl -- animated Tk view of the four pursuit trajectory
# conditions, driven live by the `traj` package. A quick way to SEE the
# dynamics (and a smoke-test of dlsh Tk + traj together).
#
#   dlsh /Users/sheinb/src/dlsh/vfs/lib/traj/demo_conditions.tcl           (matched: the 4 conditions)
#   dlsh /Users/sheinb/src/dlsh/vfs/lib/traj/demo_conditions.tcl natural   (full-path view, incl. the topple)
#
# Each panel shows the FULL path, a moving target with a short time-window
# "comet" tail (its length scales with speed), pivot+rod for the pendula, and a
# speed bar. Each condition runs for its own natural full-path duration (shown
# in the title) and loops independently: the ballistic flight (1.5 s), one full
# pendulum swing between both turns (~4.5 s), and one full inverted-pendulum
# topple through a near-complete circle (~2.5 s, needs an initial nudge -- from
# rest near the top it just hangs). Watch the speed bars/tails for the dynamics:
# hill/valley slow at the apex/trough, pendulum crawls through its turns, the
# inverted pendulum accelerates away from the top and whips through the bottom.
#
# Headless snapshot (for verification, no window needed):
#   dlsh demo_conditions.tcl -snapshot 1.0 out.ps

package require Tk
if { [catch { package require traj }] } {
    source [file join [file dirname [info script]] traj.tcl]
}

namespace eval condviz {
    variable W 940 ; variable H 620
    variable t 0.0
    variable playing 1 ; variable speed 1.0 ; variable tail 0.18
    variable conds {} ; variable c .c ; variable phase_lbl ""
    variable mode matched   ;# default "matched" (4 experimental conditions); "natural" = full-path view
}

proc condviz::d2r { d } { expr {$d*3.14159265358979/180.0} }

# --- build the four conditions and their per-panel world->pixel mappings ----
# Each condition runs for its OWN natural full-path duration and loops
# independently -- the ballistic flight, one full pendulum swing period, one
# full inverted topple. (The inverted needs an initial angular velocity: from
# rest near the top it just hangs.) So every panel shows its COMPLETE path.
proc condviz::build {} {
    variable mode
    if { $mode eq "matched" } { return [condviz::build_matched] }
    variable conds ; variable W ; variable H
    set g 9.8
    # pendulum: play one full period so the whole swing (both turns) is drawn
    set pen [traj::pendulum::make [condviz::d2r 75] 4.0 $g 1.0 -pivot_y 3.0]
    set pen_dur [expr {4.0*[dict get $pen quarterK]/[dict get $pen omega0]}]
    set pen [traj::pendulum::make [condviz::d2r 75] 4.0 $g $pen_dur -pivot_y 3.0]
    # {title  color  traj-dict  kind  duration}
    set defs [list \
      [list "Ballistic HILL   (+g)"              "#4da6ff" \
          [traj::ballistic::symmetric 9.0 1.5 $g 0 0.0]        ballistic 1.5] \
      [list "Ballistic VALLEY   (-g)"            "#ff7043" \
          [traj::ballistic::symmetric 9.0 1.5 [expr {-$g}] 0 0.0] ballistic 1.5] \
      [list "Pendulum   (full swing)"            "#66bb6a"  $pen pendulum $pen_dur] \
      [list "Inverted pendulum   (topples over)" "#ba68c8" \
          [traj::inverted_pendulum::make 0.15 4.0 $g 2.45 -pivot_y -3.0 -theta_dot0 1.5] inverted 2.45] ]
    condviz::_layout $defs
}

# THE FOUR EXPERIMENTAL CONDITIONS. Two matched pairs, each generated by
# inverting gravity: ballistic hill/valley and pendulum/anti-gravity-pendulum.
# Columns = gravity-consistent (left) vs -inconsistent (right); rows = ballistic
# (top) / pendulum (bottom). Cross-class matching is a compromise (a 1-DOF
# pendulum can't be wide+shallow+fast+short like the 2-DOF ballistic): the
# ballistic uses the pilot params (ecc 9, 1.5 s, wide-shallow-fast) and the
# pendulum is SPEED-ANCHORED (theta0~105 deg, ~3 s) so its peak speed (~12 dva/s)
# matches the ballistic -- letting DURATION float, the way extent floats for the
# ballistic. Within each pair the match is exact (the anti-pendulum is the exact
# vertical mirror of the pendulum: same speed profile, curvature flipped).
proc condviz::build_matched {} {
    set g 9.8
    set Tb 1.5      ;# ballistic (pilot): wide, shallow, fast
    set Tp 3.0      ;# pendulum: half-swing lasts Tp; speed-anchored to the ballistic
    set th0 [condviz::d2r 105]
    set qK [traj::pendulum::ellipK [expr {sin($th0/2.0)}]]
    set w0 [expr {2.0*$qK/$Tp}] ; set L [expr {$g/($w0*$w0)}]
    set pen  [traj::pendulum::make $th0 $L $g $Tp -pivot_y 0.0]
    set anti [traj::pendulum::make $th0 $L $g $Tp -pivot_y 0.0 -invert 1]
    set defs [list \
      [list "Ballistic HILL   (+g, consistent)"     "#4da6ff" \
          [traj::ballistic::symmetric 9.0 $Tb $g 0 0.0]        ballistic $Tb] \
      [list "Ballistic VALLEY   (-g, inconsistent)" "#ff7043" \
          [traj::ballistic::symmetric 9.0 $Tb [expr {-$g}] 0 0.0] ballistic $Tb] \
      [list "Pendulum   (bob below, consistent)"    "#66bb6a"  $pen  pendulum $Tp] \
      [list "Anti-gravity pendulum   (bob above, inconsistent)" "#ba68c8" $anti pendulum $Tp] ]
    condviz::_layout $defs
}

# shared 2x2 layout: compute each panel's world->pixel mapping from its defs
proc condviz::_layout { defs } {
    variable conds ; variable W ; variable H
    set cw [expr {$W/2}] ; set ch [expr {$H/2}]
    set cells { {0 0} {1 0} {0 1} {1 1} }
    set conds {}
    for { set i 0 } { $i < 4 } { incr i } {
        lassign [lindex $defs $i] title color p kind cdur
        lassign [lindex $cells $i] col row
        set x0 [expr {$col*$cw}] ; set y0 [expr {$row*$ch}]
        # plot area inside the cell (title band 26px, speed bar 14px, margins)
        set m 26
        set px0 [expr {$x0+$m}] ; set px1 [expr {$x0+$cw-$m}]
        set py0 [expr {$y0+44}]  ; set py1 [expr {$y0+$ch-30}]   ;# room for title + readout lines

        # world bbox from the trajectory (+ pivot for the pendula, so the rod fits)
        set xmin 1e9 ; set xmax -1e9 ; set ymin 1e9 ; set ymax -1e9 ; set smax 1e-6
        for { set k 0 } { $k <= 120 } { incr k } {
            set tt [expr {$cdur*$k/120.0}]
            lassign [traj::pos $p $tt] wx wy
            lassign [traj::vel $p $tt] vx vy
            set xmin [expr {min($xmin,$wx)}] ; set xmax [expr {max($xmax,$wx)}]
            set ymin [expr {min($ymin,$wy)}] ; set ymax [expr {max($ymax,$wy)}]
            set smax [expr {max($smax,hypot($vx,$vy))}]
        }
        # trajectory-only extent (for the readout), BEFORE folding in the pivot
        set txspan [expr {$xmax-$xmin}] ; set tyspan [expr {$ymax-$ymin}]
        if { $kind eq "pendulum" || $kind eq "inverted" } {
            set pvx [dict get $p pivot_x] ; set pvy [dict get $p pivot_y]
            set xmin [expr {min($xmin,$pvx)}] ; set xmax [expr {max($xmax,$pvx)}]
            set ymin [expr {min($ymin,$pvy)}] ; set ymax [expr {max($ymax,$pvy)}]
        }
        set ww [expr {max(1e-3,$xmax-$xmin)}] ; set wh [expr {max(1e-3,$ymax-$ymin)}]
        set s [expr {min(($px1-$px0)/$ww, ($py1-$py0)/$wh)}]
        lappend conds [dict create \
            title $title color $color traj $p kind $kind dur $cdur \
            s $s wcx [expr {($xmin+$xmax)/2.0}] wcy [expr {($ymin+$ymax)/2.0}] \
            pcx [expr {($px0+$px1)/2.0}] pcy [expr {($py0+$py1)/2.0}] \
            smax $smax txspan $txspan tyspan $tyspan \
            x0 $x0 y0 $y0 cw $cw ch $ch \
            sb_x0 [expr {$x0+$m}] sb_x1 [expr {$x0+$cw-$m}] sb_y [expr {$y0+$ch-20}]]
    }
}

# world -> pixel for a given condition (y flipped)
proc condviz::map { cond wx wy } {
    set s [dict get $cond s]
    list [expr {[dict get $cond pcx]+($wx-[dict get $cond wcx])*$s}] \
         [expr {[dict get $cond pcy]-($wy-[dict get $cond wcy])*$s}]
}

proc condviz::dimcolor { hex f } {          ;# blend hex toward black by factor f
    scan $hex "#%2x%2x%2x" r g b
    format "#%02x%02x%02x" [expr {int($r*$f)}] [expr {int($g*$f)}] [expr {int($b*$f)}]
}

# --- static layer: titles, borders, faint full paths, floor / pivots ---------
proc condviz::draw_static {} {
    variable c ; variable conds ; variable W ; variable H
    $c delete all
    $c configure -background "#161616"
    foreach cond $conds {
        set x0 [dict get $cond x0] ; set y0 [dict get $cond y0]
        set cw [dict get $cond cw] ; set ch [dict get $cond ch]
        $c create rectangle $x0 $y0 [expr {$x0+$cw}] [expr {$y0+$ch}] \
            -outline "#2c2c2c" -width 1
        $c create text [expr {$x0+12}] [expr {$y0+15}] -anchor w \
            -text [dict get $cond title] -fill [dict get $cond color] \
            -font {Helvetica 12 bold}
        # per-panel readout (second line): peak speed, extent (W x H), duration
        $c create text [expr {$x0+12}] [expr {$y0+32}] -anchor w \
            -text [format "peak %.1f dva/s     %.1f x %.1f dva     %.1f s" \
                [dict get $cond smax] [dict get $cond txspan] [dict get $cond tyspan] \
                [dict get $cond dur]] \
            -fill "#9a9a9a" -font {Courier 9}
        set p [dict get $cond traj] ; set kind [dict get $cond kind]
        # ballistic floor line (world y=0)
        if { $kind eq "ballistic" } {
            lassign [condviz::map $cond -100 0] fx0 fy0
            lassign [condviz::map $cond  100 0] fx1 fy1
            $c create line [dict get $cond x0] $fy0 [expr {[dict get $cond x0]+$cw}] $fy1 \
                -fill "#333333" -dash {2 3}
        }
        # faint full path (over this condition's own full duration)
        set cdur [dict get $cond dur]
        set pts {}
        for { set k 0 } { $k <= 160 } { incr k } {
            set tt [expr {$cdur*$k/160.0}]
            lassign [traj::pos $p $tt] wx wy
            lassign [condviz::map $cond $wx $wy] px py
            lappend pts $px $py
        }
        $c create line {*}$pts -fill [condviz::dimcolor [dict get $cond color] 0.35] -width 1
        # pivot marker for pendula
        if { $kind eq "pendulum" || $kind eq "inverted" } {
            lassign [condviz::map $cond [dict get $p pivot_x] [dict get $p pivot_y]] pxp pyp
            $c create oval [expr {$pxp-3}] [expr {$pyp-3}] [expr {$pxp+3}] [expr {$pyp+3}] \
                -fill "#888888" -outline ""
            $c create text [expr {$pxp+7}] $pyp -anchor w -text "pivot" -fill "#666666" -font {Helvetica 8}
        }
        # speed-bar track
        $c create rectangle [dict get $cond sb_x0] [expr {[dict get $cond sb_y]-4}] \
            [dict get $cond sb_x1] [expr {[dict get $cond sb_y]+4}] -outline "#333333" -fill "#0e0e0e"
        $c create text [dict get $cond sb_x0] [expr {[dict get $cond sb_y]-11}] -anchor w \
            -text "speed" -fill "#555555" -font {Helvetica 8}
    }
}

# --- dynamic layer at time t: comet tail, rod, target dot, speed fill --------
proc condviz::draw_dynamic {} {
    variable c ; variable conds ; variable t ; variable tail
    $c delete dyn
    foreach cond $conds {
        set p [dict get $cond traj] ; set col [dict get $cond color]
        set ph [expr {fmod($t, [dict get $cond dur])}]   ;# this panel's own phase
        # comet tail (last `tail` seconds of this panel's phase) -- length ~ speed
        set pts {}
        set t0 [expr {max(0.0,$ph-$tail)}]
        for { set k 0 } { $k <= 10 } { incr k } {
            set tt [expr {$t0+($ph-$t0)*$k/10.0}]
            lassign [traj::pos $p $tt] wx wy
            lassign [condviz::map $cond $wx $wy] px py
            lappend pts $px $py
        }
        if { [llength $pts] >= 4 } {
            $c create line {*}$pts -fill [condviz::dimcolor $col 0.7] -width 3 \
                -capstyle round -tags dyn
        }
        lassign [traj::pos $p $ph] wx wy
        lassign [condviz::map $cond $wx $wy] px py
        # rod for pendula (pivot -> bob)
        if { [dict get $cond kind] in {pendulum inverted} } {
            lassign [condviz::map $cond [dict get $p pivot_x] [dict get $p pivot_y]] pxp pyp
            $c create line $pxp $pyp $px $py -fill "#666666" -width 1 -tags dyn
        }
        # target dot
        $c create oval [expr {$px-7}] [expr {$py-7}] [expr {$px+7}] [expr {$py+7}] \
            -fill $col -outline "white" -width 1 -tags dyn
        # speed-bar fill
        lassign [traj::vel $p $ph] vx vy
        set frac [expr {hypot($vx,$vy)/[dict get $cond smax]}]
        set x1 [expr {[dict get $cond sb_x0]+($frac)*([dict get $cond sb_x1]-[dict get $cond sb_x0])}]
        $c create rectangle [dict get $cond sb_x0] [expr {[dict get $cond sb_y]-4}] \
            $x1 [expr {[dict get $cond sb_y]+4}] -outline "" -fill $col -tags dyn
    }
}

proc condviz::redraw {} { condviz::draw_dynamic }

proc condviz::tick {} {
    variable playing ; variable t ; variable speed ; variable phase_lbl ; variable c
    # window closed -> the whole Tk app may be torn down, so even `winfo` can
    # throw ("application has been destroyed"). Catch it and stop the loop.
    if { [catch { winfo exists $c } ok] || !$ok } return
    if { $playing } {
        set t [expr {$t + 0.02*$speed}]
        if { $t > 1.0e6 } { set t 0.0 }        ;# free-running clock; each panel does its own fmod
    }
    condviz::redraw
    if { $phase_lbl ne "" } {
        $phase_lbl configure -text [format "clock = %6.2f s  (panels loop independently)" $t]
    }
    after 20 condviz::tick
}

# --- GUI ---------------------------------------------------------------------
proc condviz::gui {} {
    variable W ; variable H ; variable c ; variable phase_lbl ; variable speed
    wm title . "traj -- four pursuit conditions"
    wm protocol . WM_DELETE_WINDOW { exit 0 }   ;# clean shutdown on window close
    canvas $c -width $W -height $H -highlightthickness 0
    pack $c -side top
    set f .ctl ; frame $f -padx 8 -pady 6 ; pack $f -side top -fill x
    button $f.pp -text "Pause" -width 7 -command {
        set condviz::playing [expr {!$condviz::playing}]
        .ctl.pp configure -text [expr {$condviz::playing ? "Pause" : "Play"}]
    }
    button $f.rs -text "Restart" -width 7 -command { set condviz::t 0.0 }
    label  $f.sl -text "speed"
    scale  $f.sc -from 0.25 -to 2.0 -resolution 0.05 -orient horizontal \
        -length 180 -variable condviz::speed -showvalue 1
    set phase_lbl [label $f.ph -text "" -width 44 -anchor e -font {Courier 11}]
    pack $f.pp $f.rs -side left -padx 3
    pack $f.sl -side left -padx {12 2} ; pack $f.sc -side left
    pack $f.ph -side right
    condviz::build ; condviz::draw_static ; condviz::redraw
}

# --- entry point: interactive, or a one-frame headless snapshot --------------
# Default is the matched 4-condition design; pass "natural" for the full-path
# view (incl. the topple inverted pendulum).
if { [set mi [lsearch $::argv natural]] >= 0 } {
    set condviz::mode natural ; set ::argv [lreplace $::argv $mi $mi]
} elseif { [set mi [lsearch $::argv matched]] >= 0 } {
    set condviz::mode matched ; set ::argv [lreplace $::argv $mi $mi]
}
if { [lindex $::argv 0] eq "-snapshot" } {
    set condviz::t [lindex $::argv 1] ; set out [lindex $::argv 2]
    wm withdraw .
    canvas $condviz::c -width $condviz::W -height $condviz::H -highlightthickness 0
    condviz::build ; condviz::draw_static ; condviz::redraw ; update idletasks
    $condviz::c postscript -file $out -colormode color \
        -width $condviz::W -height $condviz::H -pagewidth 9.4i
    puts "wrote $out" ; exit 0
} else {
    condviz::gui
    # Realize/map the window BEFORE the animation loop starts. On macOS/Aqua the
    # window comes up during the event loop, and starting after-scheduled draws
    # before it is mapped can hit a transiently-missing ".c". `update` forces a
    # synchronous realize (and returns -- unlike `tkwait visibility`, which would
    # hang if the window never maps); `tick` also guards on `winfo exists`.
    update
    condviz::tick
    vwait condviz::forever
}
