name: Release for Linux

on:
  push:
    tags:
      - '*'

jobs:

  release:

    strategy:
      matrix:
        # Build on not-the-latest to keep dependency versions modest.
        os: [ubuntu-22.04, ubuntu-22.04-arm]

    runs-on: ${{ matrix.os }}

    permissions:
        contents: write

    steps:

      - name: Set up a build environment.
        run: |
          sudo apt update
          sudo apt install -y build-essential cmake zip
          sudo apt install -y zlib1g-dev liblz4-dev tk-dev libyajl-dev
          sudo apt install -y libpango1.0-dev libwayland-dev wayland-protocols libxkbcommon-dev libxinerama-dev libdbus-1-dev libglew-dev libdecor-0-dev libgtk-3-dev
          sudo apt install -y libpq-dev
          # Add Arrow installation
          sudo apt install -y ca-certificates lsb-release wget
          wget https://apache.jfrog.io/artifactory/arrow/$(lsb_release --id --short | tr 'A-Z' 'a-z')/apache-arrow-apt-source-latest-$(lsb_release --codename --short).deb
          sudo apt install -y ./apache-arrow-apt-source-latest-$(lsb_release --codename --short).deb
          sudo apt update
          sudo apt install -y libarrow-dev
    
      - name: Check out our dlsh code for the current tag..
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install TCL 9 to the build environment.
        run: |
          cd deps/tcl/unix/
          ./configure
          make
          sudo make install

      - name: Install Jansson to the build environment.
        run: |
          cd deps/jansson/
          cmake -B build
          cmake --build build
          sudo cmake --install build

      - name: Install Libharu to the build environment.
        run: |
          cd deps/libharu/
          cmake -D BUILD_SHARED_LIBS=OFF -D CMAKE_POSITION_INDEPENDENT_CODE=ON -B build
          cmake --build build
          sudo cmake --install build

      - name: Install box2d v3 static lib into the build environment.
        run: |
          cd deps/box2d
          mkdir build
          cmake -B build -D BOX2D_UNIT_TESTS=OFF -D BOX2D_SAMPLES=OFF -D BOX2D_BENCHMARKS=OFF -D BUILD_SHARED_LIBS=OFF
          cmake --build build --parallel
          sudo cmake --install build

      - name: Install FLTK GUI framework into the build environment.
        run: |
          cd deps/fltk/
          cmake -B build
          cmake --build build
          sudo cmake --install build

      - name: Checkout dependencies not available from public repos
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/dlsh-dependencies
          token: ${{ secrets.DLSH_DEPENDENCIES_TOKEN }}
          path: deps/dlsh-dependencies

      - name: Build dlsh and package for release.
        run: |
          cmake -B build -D PROJECT_VERSION=${{ github.ref_name }} -D DLSH_DEPENDENCIES=${{ github.workspace }}/deps/dlsh-dependencies -D CPACK_DEB_COMPONENT_INSTALL=ON -D CPACK_COMPONENTS_ALL="dlsh;dg"
          cmake --build build
          cpack -G DEB --config build/CPackConfig.cmake

          cmake -B build -D PROJECT_VERSION=${{ github.ref_name }} -D DLSH_DEPENDENCIES=${{ github.workspace }}/deps/dlsh-dependencies -D CMAKE_INSTALL_PREFIX=build/dlsh-zip
          cmake --install build --component dlsh-zip
          cd build/dlsh-zip/
          zip -r dlsh-${{ github.ref_name }}-Linux-$(dpkg --print-architecture).zip lib/

      - name: Create a GitHub release for the current tag and artifacts.
        uses: ncipollo/release-action@v1
        with:
          artifacts: "*.deb, build/dlsh-zip/*.zip"
          body: libs, headers and dependencies for dlsh version ${{ github.ref_name }}
          generateReleaseNotes: true
          allowUpdates: true
